# Site settings
title: Crafting Labs le blog
email: hello@crafting-labs.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.crafting-labs.fr" # the base hostname & protocol for your site
twitter_username: avernois
github_username:  avernois

# Build settings
markdown: kramdown

permalink:  /:year/:month/:day/:title
paginate:  10
excerpt_separator: "\n\n\n"


pages_list:
  Contact: '/contact'